### ISSUE TITLE
document icons

### ISSUE THREAD

**Issue by okonomiyaki3000** [facelessuser/Aprosopo#13]
My document icons have disappeared for js, css, and html files. Possibly others too but I still have them for unknown types, png, svg, ttf, and some others. Is it just me?

**Comment by facelessuser** [comment]
What do you mean disappear?  I still have icons for js, css, and html.  I have not changed anything dealing with icons for a good long while now.  Are you sure you didn't install a package override theme icons?

**Comment by okonomiyaki3000** [comment]
It could be interference from some other plugin but it's weird because, if I use a different theme (preap, for example), I get icons.

**Comment by facelessuser** [comment]
Maybe Sublime is caching a corrupted state on your machine.  Icons work fine for me on all my systems; I am on the latest release.  I don't do anything funny with icons either.  I just provide the override icons, and Sublime automatically uses them and overrides the builtin ones; that is it.  I don't provide any special rules for language icons or anything.

I would try clearing your cache for Aprosopo.  In the console you can find your cache path by entering: `sublime.cache_path()`.  I would then just delete the Aprosopo folder and try and restart and see if that helps.

**Comment by okonomiyaki3000** [comment]
I solved it. I decided to try disabling things and when I got to Preap (a different theme) my icons came back. I guess there must be something wrong with that theme.
