### ISSUE TITLE
resizable status bar fonts

### ISSUE THREAD

**Issue by jimpriest** [facelessuser/Aprosopo#14]
This is still my favorite theme and I've been using more plugins which utilize the status bar.

Is it possible to make that font size a configurable setting?

**Comment by facelessuser** [comment]
Should be.  I will look into it when I get some time.

**Comment by facelessuser** [comment]
[`st3-1.8.0`](https://github.com/facelessuser/Aprosopo/releases/tag/st3-1.8.0). Done :smile:.
